/* tslint:disable */
/* eslint-disable */
/**
 * Irembo Account-Management Service
 * This service provides endpoints for all `account management` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { User } from './user';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * Indicates if login strategy is passwordless or with password
     * @type {boolean}
     * @memberof LoginResponse
     */
    isPasswordless?: boolean;
    /**
     * 
     * @type {User}
     * @memberof LoginResponse
     */
    user?: User;
    /**
     * User authentication token (JWT). This will be a custom token for accessing AUTH VERIFY-2FA
     * @type {string}
     * @memberof LoginResponse
     */
    token?: string;
    /**
     * 2FA setup code for setting-up TOTP QR-CODE (only provided when 2FA has not been setup)
     * @type {string}
     * @memberof LoginResponse
     */
    twoFaSetupCode?: string;
}
