/* tslint:disable */
/* eslint-disable */
/**
 * Irembo Account-Management Service
 * This service provides endpoints for all `account management` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Gender } from './gender';
import { MaritalStatus } from './marital-status';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * User unique identifier
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * User's email
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * Indicates if user is an admin or just a normal user
     * @type {boolean}
     * @memberof User
     */
    isAdmin: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    verified: boolean;
    /**
     * User's first-name
     * @type {string}
     * @memberof User
     */
    firstName?: string;
    /**
     * User's last-name
     * @type {string}
     * @memberof User
     */
    lastName?: string;
    /**
     * User's photo or picture url
     * @type {string}
     * @memberof User
     */
    photoUrl?: string;
    /**
     * 
     * @type {Gender}
     * @memberof User
     */
    gender?: Gender;
    /**
     * User's date of birth
     * @type {string}
     * @memberof User
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {MaritalStatus}
     * @memberof User
     */
    maritalStatus?: MaritalStatus;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updatedAt?: Date;
}
