/* tslint:disable */
/* eslint-disable */
/**
 * Irembo Account-Management Service
 * This service provides endpoints for all `account management` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VerifyAccountDto
 */
export interface VerifyAccountDto {
    /**
     * User's identifier
     * @type {string}
     * @memberof VerifyAccountDto
     */
    userId: string;
    /**
     * Verify-token to activate account
     * @type {string}
     * @memberof VerifyAccountDto
     */
    token: string;
}
