/* tslint:disable */
/* eslint-disable */
/**
 * Irembo Account-Management Service
 * This service provides endpoints for all `account management` related interactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: fatai@mail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccountVerificationRequest } from './account-verification-request';
/**
 * 
 * @export
 * @interface VerificationRequestsResponse
 */
export interface VerificationRequestsResponse {
    /**
     * 
     * @type {Array<AccountVerificationRequest>}
     * @memberof VerificationRequestsResponse
     */
    records: Array<AccountVerificationRequest>;
}
